/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int n) {
        int[] num = new int[n];
        for(int i = 0; i < n; i++) {
            num[i] = getRandomNumber();
        }
        return num;
    }

    public static int getRandomNumber(){
        int x = (int) (Math.random()*((6-1)+1))+1;
        return x;
    }

    public static boolean containsDuplicates(int[] inputArr) {
        for (int i = 0; i < inputArr.length; i++) {
            for (int j = 0; j < inputArr.length; j++) {
                if (i != j) {
                    if (inputArr[i] == inputArr[j]) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static int calculateAverage(int[] inputArr) {
        int sum = 0;
        for(int i = 0; i < inputArr.length; i++) {
            sum += inputArr[i];
        }
        return sum/inputArr.length;
    }

    public int [] twoDArray(int[][] inputArr) {
        double currentAverage = 0;
        double previousAverage = 0;
        int[] resultArray = {};
        boolean firstTime = true;

        for(int i = 0; i < inputArr.length; i++) {
            currentAverage = calculateAverage(inputArr[i]);
            if(firstTime){
                previousAverage = currentAverage;
                resultArray = inputArr[i];
                firstTime = false;
            }
            ;
            if(currentAverage < previousAverage){
                resultArray = inputArr[i];
                previousAverage = currentAverage;
            }
        }
        return resultArray;

    }
}
